title: EFH Kiefer
views:
  - title: Luftqualit√§t
    theme: dark-mode
    cards: 
      - type: entities
        entities:
          - sensor.co2_essbereich_2
          - sensor.co2_flur_og_2
       